# Fundamentals of tensor operations using Pytorch and Numpy.

In [2]:
import torch
import numpy as np
import time

## List vs Array vs Tensor

In [3]:
# List vs Array vs Tensor
N = 1000000 

# Python List
list_one = list(range(N))
list_two = list(range(N))

start_time = time.time()
python_list_result = [a + b for a, b in zip(list_one, list_two)]
end_time = time.time()
list_time = end_time - start_time
print(f"Python List took: {list_time:.6f} seconds")

# Numpy Array
# Numpy arrays are homogeneous and stored in a contiguous memory block.
# Operations are executed by highly optimized, pre-compiled C code.
numpy_array_one = np.arange(N)
numpy_array_two = np.arange(N)

start_time = time.time()
numpy_array_result = numpy_array_one + numpy_array_two
end_time = time.time()
numpy_time = end_time - start_time
print(f"Numpy Array took: {numpy_time:.6f} seconds")

# Pytorch Tensor
# Pytorch tensors are similar to Numpy arrays but with added features for
# deep learning, like GPU acceleration and automatic differentiation.
pytorch_tensor_one = torch.arange(N)
pytorch_tensor_two = torch.arange(N)

start_time = time.time()
pytorch_tensor_result = pytorch_tensor_one + pytorch_tensor_two
end_time = time.time()
tensor_time = end_time - start_time
print(f"Pytorch Tensor (CPU) took: {tensor_time:.6f} seconds")


Python List took: 0.043476 seconds
Numpy Array took: 0.001603 seconds
Pytorch Tensor (CPU) took: 0.000710 seconds


## Create 1 D,2D and 3D tensors using Pytorch and Numpy.

In [4]:
# 1D Tensor
tensor_1d_torch = torch.tensor([1, 2, 3, 4, 5])
print(f"1D Tensor: {tensor_1d_torch}")

# 2D Tensor
tensor_2d_torch = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"2D Tensor:\n{tensor_2d_torch}")

# 3D Tensor
tensor_3d_torch = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"3D Tensor:\n{tensor_3d_torch}")

# nth Dimensional tensor
tensor_nd_torch = torch.randn(2, 3, 4, 5)
print(f"nD Tensor shape: {tensor_nd_torch.shape}")

1D Tensor: tensor([1, 2, 3, 4, 5])
2D Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
3D Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
nD Tensor shape: torch.Size([2, 3, 4, 5])


## Show basic operations : Element wise operations.

In [ ]:

# Tensor addition
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])
tensor_sum = tensor_a + tensor_b

# Tensor subtraction
tensor_diff = tensor_a - tensor_b

# Tensor multiplication
tensor_mul = tensor_a * tensor_b

# Tensor division
tensor_div = tensor_a / tensor_b

# Tensor dot product
tensor_dot = torch.dot(tensor_a, tensor_b)

# Tensor matrix multiplication
tensor_matmul = torch.matmul(tensor_2d_torch, tensor_2d_torch.T)

print(f"Tensor Sum: {tensor_sum}")
print(f"Tensor Difference: {tensor_diff}")
print(f"Tensor Multiplication: {tensor_mul}")
print(f"Tensor Division: {tensor_div}")
print(f"Tensor Dot Product: {tensor_dot}")
print(f"Tensor Matrix Multiplication:\n{tensor_matmul}")

Tensor Sum: tensor([5, 7, 9])
Tensor Difference: tensor([-3, -3, -3])
Tensor Multiplication: tensor([ 4, 10, 18])
Tensor Division: tensor([0.2500, 0.4000, 0.5000])
Tensor Dot Product: 32
Tensor Matrix Multiplication:
tensor([[14, 32],
        [32, 77]])


## Indexing and slicing operations( Boolean Masking, extracting subtensor.. etc)

In [6]:

# Boolean Masking
mask = tensor_1d_torch > 2
masked_tensor = tensor_1d_torch[mask]

# Extracting subtensor
sub_tensor = tensor_2d_torch[:, 1:]

# Concatenating tensors
concatenated_tensor = torch.cat((tensor_a, tensor_b), dim=0)

# Stacking tensors
stacked_tensor = torch.stack((tensor_a, tensor_b), dim=0)

print(f"Masked Tensor: {masked_tensor}")
print(f"Sub Tensor:\n{sub_tensor}")
print(f"Concatenated Tensor: {concatenated_tensor}")
print(f"Stacked Tensor:\n{stacked_tensor}")

Masked Tensor: tensor([3, 4, 5])
Sub Tensor:
tensor([[2, 3],
        [5, 6]])
Concatenated Tensor: tensor([1, 2, 3, 4, 5, 6])
Stacked Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])


## Use .view, .reshape .unsqueeze and squeeze function in pytorch

In [ ]:

# .view
viewed_tensor = tensor_2d_torch.view(3, 2)

# .reshape
reshaped_tensor = tensor_2d_torch.reshape(3, 2)

# .unsqueeze
unsqueezed_tensor = tensor_1d_torch.unsqueeze(0)

# .squeeze
squeezed_tensor = unsqueezed_tensor.squeeze(0)

print(f"Viewed Tensor:\n{viewed_tensor}")
print(f"Reshaped Tensor:\n{reshaped_tensor}")
print(f"Unsqueezed Tensor:\n{unsqueezed_tensor}")
print(f"Squeezed Tensor:\n{squeezed_tensor}")

Viewed Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])
Reshaped Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])
Unsqueezed Tensor:
tensor([[1, 2, 3, 4, 5]])
Squeezed Tensor:
tensor([1, 2, 3, 4, 5])


## Compare with .reshape in numpy

In [ ]:
tensor_c = torch.tensor([[1, 2, 3], [4, 5, 6]])
reshaped_tensor = tensor_c.reshape(3, 2)

print(f"Original Tensor:\n{tensor_c}")
print(f"Reshaped Tensor:\n{reshaped_tensor}")

numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
numpy_reshaped = numpy_array.reshape(3, 2)

print(f"Original Numpy Array:\n{numpy_array}")
print(f"Numpy Reshaped Array:\n{numpy_reshaped}")


Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Reshaped Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])
Original Numpy Array:
[[1 2 3]
 [4 5 6]]
Numpy Reshaped Array:
[[1 2]
 [3 4]
 [5 6]]


## Broadcasting

In [10]:

tensor_c = torch.tensor([[1], [2], [3]])
tensor_d = torch.tensor([10, 20, 30])
broadcasted_sum = tensor_c + tensor_d

print(f"Broadcasted Sum:\n{broadcasted_sum}")

Broadcasted Sum:
tensor([[11, 21, 31],
        [12, 22, 32],
        [13, 23, 33]])


## In place vs out of place operations

In [13]:
# In-place operation
tensor_inplace = torch.tensor([1, 2, 3])
tensor_inplace.add_(5)  # modifies tensor_inplace directly

print(f"In-place Modified Tensor: {tensor_inplace}")

# Out-of-place operation
tensor_outofplace = torch.tensor([1, 2, 3])
tensor_new = tensor_outofplace + 5  # creates a new tensor

print(f"Out-of-place New Tensor: {tensor_new}")

In-place Modified Tensor: tensor([6, 7, 8])
Out-of-place New Tensor: tensor([6, 7, 8])
